
services:
  redis:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  hxarc:
    build: .
    image: hx/hxarc:dev
    command: ["./docker_entrypoint.sh"]
    volumes:
      - .:/code
      - data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      HXARC_DOTENV_PATH: "/code/docker_dotenv.env"
      REDIS_URL: "redis://redis:6379/0"
    networks:
      default:
      public:
        aliases:
          - hxarc.localhost

volumes:
  redis-data:
  data:

networks:
  public:
