---
version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: hxarc.log
        maxBytes: 10485760 #10MB
        backupCount: 7
        encoding: utf8

loggers:
    hxarc:
        level: DEBUG
        handlers: [console, error_file_handler]
        propagate: no

    root:
        level: DEBUG
        handlers: [console]






