# Generated by Django 4.2.16 on 2024-11-22 00:11

from django.db import migrations, models
import hxarc.apps.hxlti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consumer', models.CharField(default=hxarc.apps.hxlti.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('secret_key', models.CharField(default=hxarc.apps.hxlti.models.generate_id, max_length=128)),
                ('expire_on', models.DateTimeField(default=hxarc.apps.hxlti.models.expire_in_weeks)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
